### ISSUE TITLE
Number of iterations for training

### ISSUE THREAD

**Issue by zheyong91** [AYLIEN/docnade#1]
Hi. 

First of all. I hav read your articles and find it to be well written. I faced some issues when training the model. I have split my datasets of 900 articles into the 3 csv files needed. After which i ran the preprocess python file and then ran the training file. This where i faced some issues. It seems that the training process is stuck in an infinite loop. The number of iterations is 10000+ and counting. With the output of every 50 iterations being 0 and 0. I would like to seek your advise on could there be potentially anything wrong with my implementation?

**Comment by johnglover** [comment]
@zheyong91: Thanks. It's hard to say without looking at your data in detail, but you should compare against runs on the 20 Newsgroups dataset and see what is different. I'm not really sure how it could possibly be in an infinite loop, but note that training defaults to 50000 steps (https://github.com/AYLIEN/docnade/blob/master/train.py#L138). A loss of 0 sounds suspicious though, I expect that there is something wrong with the data.
