### ISSUE TITLE
how to make or get the train/valid/test csv files

### ISSUE THREAD

**Issue by loveJasmine** [AYLIEN/docnade#6]

**Comment by johnglover** [comment]
These files are just one example per line CSVs, so something like:

label1,"this is the text of the document"
label2,"this is the text of the second document"

I'm not sure which specific files you are referring to, but 20 newsgroups for example you can get from here: http://qwone.com/~jason/20Newsgroups/

**Comment by loveJasmine** [comment]
but no csv find in ttp://qwone.com/~jason/20Newsgroups/ or its *.tgz files

**Comment by johnglover** [comment]
@loveJasmine Yes you will need to convert the data yourself in this instance.
