### ISSUE TITLE
Bug in preprocess.py

### ISSUE THREAD

**Issue by ArtyomLobanov** [AYLIEN/docnade#8]
Hello!
I have found a problem in **preprocess.py**. As you can see, the id of the first word from .vocab file will be equal to 0.
```python
def main(args):
    ...
    with open(args.vocab, 'r') as f:
        vocab = [w.strip() for w in f.readlines()]
    vocab_to_id = dict(zip(vocab, range(len(vocab))))
```
Now lets take a look at method _preprocess_
```python
def preprocess(text, vocab_to_id):
    ids = [vocab_to_id.get(x) for x in tokens(text) if vocab_to_id.get(x)]
```
It looks like in list generation construction you wanted to check if _vocab_to_id.get(x)_ is not None, but unfortunately integer value 0 will be automatically converted to False too, so words with id=0 will be ignored.

Example:
_example.vocab_
```
a
b
```
_input/training.csv_
```
mark, a a a a b b b b
```
Produced _output/training_
```
0,1 1
```

Thank you!

**Comment by johnglover** [comment]
@ArtyomLobanov: Thanks, fixed in master.
